env:
  browser: true
  es2021: true
  'vue/setup-compiler-macros': true
  'googleappsscript/googleappsscript': true

parser: 'vue-eslint-parser'

parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module

plugins:
  - vue
  - googleappsscript

extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:vue/vue3-strongly-recommended'
  - 'plugin:vue/vue3-essential'
  - 'plugin:vue/base'
  - 'plugin:prettier'
  - 'prettier'

rules:
  'no-unused-vars': 'off'
